### ISSUE TITLE
You could turn this into a generator

### ISSUE THREAD

**Issue by timsuchanek** [IBM/prisma-schema-transformer#1]
Hi @ExiaSR , this is an awesome project!

You might not be aware of it, but we have a generator architecture in Prisma, which allows you to hook into the `generate` step.

It might be interesting for you to do the schema transformation on every generate.

Here is an example: https://github.com/timsuchanek/minimal-generator

It could, of course, be, that you want to run `prisma-schema-transformer` as a one-of thing, then it doesn't make sense. But I just wanted to make you aware, that this option exists.

**Comment by ExiaSR** [comment]
@timsuchanek 

The `generator` seems interesting. If we can tap the transformation into the generator, it will definitely improve the experience, cuz the process right now is still quite cumbersome.

Thanks for letting me know! I can take a look.

**Comment by ExiaSR** [comment]
> Hi @ExiaSR , this is an awesome project!
> 
> You might not be aware of it, but we have a generator architecture in Prisma, which allows you to hook into the `generate` step.
> 
> It might be interesting for you to do the schema transformation on every generate.
> 
> Here is an example: [timsuchanek/minimal-generator](https://github.com/timsuchanek/minimal-generator)
> 
> It could, of course, be, that you want to run `prisma-schema-transformer` as a one-of thing, then it doesn't make sense. But I just wanted to make you aware, that this option exists.

I guess the easiest way to hook into the `generate` step would be transforming the `DMMF` in the `onGenerate` hook, then somehow pass the transformed `DMMF` to the built-in generator, `prisma-client-js`.

However, I am having a hard time to figure out how to invoke the built-in generator, the [generateClient](https://github.com/prisma/prisma/blob/2.0.0-beta.9/src/packages/client/src/generator.ts#L26). It seems like the method is not exposed from the `@prisma/client` library. What would you suggest?
